### ISSUE TITLE
Registry Scan fails on parsing URL for ECR

### ISSUE THREAD

**Issue by NeutralMindFlayer** [kubescape/operator#216]
# Description
I followed the instructions on this [docs-page](https://hub.armosec.io/docs/registry-vulnerability-scan#add-and-scan-a-public-registry) for adding a public ECR repository using the same repository as on the documenation.

![image](https://github.com/kubescape/operator/assets/145658035/7d3e14ba-a88b-4ea3-8d9e-cf23adc4f440)
On the Test-Registry-Connectity step it fails with failing to get `https://https/v2/". So I have a strong assumption that it's related to the url parsing.
![image](https://github.com/kubescape/operator/assets/145658035/f690bc41-8e01-4962-9e09-91747ceb7e15)

I assume this is an operator issue, as there was no reaction on the side of Kubevuln.

# Environment
OS: `Windows Docker-Desktop K8s Cluster`
Version: ` v1.18.6` <!-- Helm Chart Version
 
# Steps To Reproduce
Follow the instructions of the [Documentation](https://hub.armosec.io/docs/registry-vulnerability-scan#add-and-scan-a-public-registry).
It should fail on the registry-test-connectivity page failing to parse.

**Comment by matthyx** [comment]
@NeutralMindFlayer did ARMO support help you on that?

**Comment by matthyx** [comment]
closing for lack of information
